spring.application.name=biblioteca
spring.datasource.url=jdbc:postgresql://dpg-d83hc0svikkc739gadqg-a.oregon-postgres.render.com/atl_ot8t
spring.datasource.username=atl_ot8t_user
spring.datasource.password=f9XCxkOBaWkqmesBP39rn3krDrKGgqLM
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
springdoc.swagger-ui.path=/aula/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true

#a mudança para none para evitar a criação automática do banco de dados
